name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker Image
        run: docker build -t my-spring-app .

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 my-spring-app

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run LEAP.postman_collection.json --env-var "baseUrl=http://localhost:8080"
