name: Automated API tests using Postman CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-66eaa850cd772c000125bc9c-da3b5f5b9a6c14d75730f5af48e8dafeea
      - name: Run API tests
        run: |
          postman collection run "3344064-2942e93c-ae98-4411-90d5-4f03782b58f2"
